export const portfolioProjects = [
  {
    id: 1,
    title: "Popsicle",
    category: "3D Model",
    description: "Vibrant 3D modeled popsicle with glossy, colorful materials.",
    splineUrl: "https://my.spline.design/popsicle-TNJl1oDFV6ksxJDDIjgzOIHa/",
    darkText: false,
  },
  {
    id: 2,
    title: "Lightning Bolt",
    category: "Lighting Effects",
    description: "Black shiny bolt with dynamic electricity and glow effects.",
    splineUrl: "https://my.spline.design/bigboilightningbolt-289hXqbKEURrHAVkTKdXmQLr/",
    darkText: false,
  },
  {
    id: 3,
    title: "Glowing Spheres",
    category: "Lighting Effects",
    description: "Luminous spheres with soft bloom lighting, depth, and subtle glow.",
    splineUrl: "https://my.spline.design/glowingspheres-ilhJuYf6E5p2r3wYhArHpS3S/",
    darkText: false,
  },
  {
    id: 4,
    title: "Glass Cube",
    category: "Materials & Shaders",
    description: "Transparent cube with realistic light refraction and reflections.",
    splineUrl: "https://my.spline.design/3dglasscube-NJLoW4iDA0HgJxLakYrcSZAQ/",
    darkText: true,
  },
  {
    id: 5,
    title: "3D Toggle Button",
    category: "UI / Interactive",
    description: "Fully interactive 3D toggle switch with satisfying click animations.",
    splineUrl: "https://my.spline.design/3dtogglebutton-35iKWQNcRsW7Ph5eM8f0yXAy/",
    darkText: true,
  },
  {
    id: 6,
    title: "Interactive 3D Boxes",
    category: "UI / Interactive",
    description: "Click to interact with a stack of responsive 3D boxes.",
    splineUrl: "https://my.spline.design/interactive3dboxes-wamaMadMNEseQXt34RI7nlX4/",
    darkText: false,
  },
  {
    id: 7,
    title: "Interactive Particle Emitter",
    category: "Particles & VFX",
    description: "Real-time particle system that reacts and trails cursor movement.",
    splineUrl: "https://my.spline.design/particleemmiter-2QSmnPT6GkPFjoIfxm6Y2Gc5/",
    darkText: false,
  },
  {
    id: 8,
    title: "Blobs",
    category: "Organic Forms",
    description: "Morphing organic blobs with fluid motion and soft ambient lighting.",
    splineUrl: "https://my.spline.design/blobs-31AeKgftUi1jLt9rFTllw15r/",
    darkText: false,
  },
  {
    id: 9,
    title: "Mini House",
    category: "Architecture",
    description: "Detailed miniature house with warm interior lighting and cosy feel.",
    splineUrl: "https://my.spline.design/minihouse-4qJO5LEdaCsuvHs27AyXb5Uv/",
    darkText: false,
  },
  {
    id: 10,
    title: "Liquid Glass",
    category: "Materials & Shaders",
    description: "Fluid glass simulation — drag and drop to interact with the scene.",
    splineUrl: "https://my.spline.design/liquidglass-hzheaGQBovEUVKgWmbAAtCpc/",
    viewerUrl: "https://prod.spline.design/Axit6venUKxY8Ahz/scene.splinecode",
    darkText: false,
  },
];

export const contactEmail = "lukacianfarani@gmail.com";
